name: pipeline

on:
  push:
    branches:
      - !main
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  pipeline:
    uses: tdpauw/reusable_workflows/.github/workflows/pipeline.yml@main
    secrets: inherit
